### ISSUE TITLE
Swifty fonts fail to install (2.1.5.2)

### ISSUE THREAD

**Issue by ryanparsons7** [headswe/Swifty#174]
With fresh installs of 2.1.5.2, upon installation of Swifty and launching, a cmd window flashes and Swifty does not open.

Font fixer doesn't work to fix the issue, manual installation of the fonts from the directory is needed.

**Comment by headswe** [comment]
Noticed it too, thanks for making a issue.

**Comment by Grollig** [comment]
Error still present in 2.1.5.3

Since today, when launching Swifty from the desktop (Target: C:\Users\XXXXXXX\AppData\Local\Swifty\Update.exe --processStart "Swifty.exe"), it gets caught in an open-window-close-window loop (loop of four or five windows, each popping up for a splitsecond, saying something about Swifty installing fonts). 

My system stays responsive, but the loop of popping windows can only be aborted by pressing CTRL-ALT-DEL and logging out as Windows user.

When "manually" launching Swifty 2.1.4.9 (Swifty.exe in Folder app-2.1.4.9) Swifty will start, but it will show "Error - Repo Version mismatch" under our mainserver repository (launching the game with this repo is possible though).

**Comment by headswe** [comment]
Try running this command.
```REG DELETE "HKEY_LOCAL_Machine\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts" /v "FontAwesome (TrueType)"``` in a admin commandline

**Comment by headswe** [comment]
[FontFixer.zip](https://github.com/headswe/Swifty/files/799385/FontFixer.zip)
Special version, runs this and then upload out.txt, please.

**Comment by headswe** [comment]
Try in 2154

**Comment by Grollig** [comment]
Sorry, I was busy over the day. I had already fixed the problem by manually deleting the fonts from my system, so I can't check the suggested fixes. However, members of my group have reported the window-loop error did not occur in 2.1.5.5, so I think it is solved by now. Anyway, thanks for your care and your quick response. Swifty is a great tool and we really appreciate your work!

**Comment by headswe** [comment]
Thanks by the way ;)
